"""Data models for payloads, scan results, findings, and evaluation metrics."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class Payload:
    """Represents a single security test payload.

    Attributes:
        id: Unique identifier for payload (e.g. 'LLM01-001').
        category: Vulnerability category (e.g. 'prompt_injection').
        owasp_id: OWASP Top 10 for LLM mapping (e.g. 'LLM01').
        prompt: Raw prompt text to send to target.
        severity: Severity rating ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW').
        heuristic_keywords: Keywords to look for in response.
        requires_llm_judge: Flag indicating if LLM judge is required for evaluation.
        expected_vulnerable: Ground truth label from benchmark datasets (True=harmful/jailbreak, False=benign refusal).
        source: Benchmark source name (e.g. 'HarmBench', 'AdvGLUE', 'JailbreakBench', 'Custom').
    """
    id: str
    category: str
    owasp_id: str
    prompt: str
    severity: str = "HIGH"
    heuristic_keywords: List[str] = field(default_factory=list)
    requires_llm_judge: bool = False
    expected_vulnerable: Optional[bool] = None
    source: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert Payload instance to dictionary."""
        d = {
            "id": self.id,
            "category": self.category,
            "owasp_id": self.owasp_id,
            "prompt": self.prompt,
            "severity": self.severity,
            "heuristic_keywords": self.heuristic_keywords,
            "requires_llm_judge": self.requires_llm_judge,
        }
        if self.expected_vulnerable is not None:
            d["expected_vulnerable"] = self.expected_vulnerable
        if self.source is not None:
            d["source"] = self.source
        return d


@dataclass
class Finding:
    """Represents the evaluation result of running a payload against a target.

    Attributes:
        payload: The Payload instance tested.
        response_text: Raw text extracted from the target's response.
        vulnerable: Flag indicating if vulnerability was detected.
        severity: Assigned severity rating.
        confidence: Confidence score (0.0 to 1.0).
        judge_type: Evaluation mechanism used ('heuristic', 'llm', 'llm_likert', 'fast_prefilter', etc.).
        reasoning: Explanation for why payload was flagged or passed.
        error: Error message if request or evaluation failed.
        converter_used: Name of converter used (e.g. 'base64', 'leetspeak') or None for plain text baseline.
        original_prompt: Original pre-conversion attack prompt text if converted, or None.
        likert_score: Graduated severity score (0 to 4).
        sent_prompt: The exact prompt string transmitted over the wire to the target model.
        target_prompt_tokens: Tokens sent to the target endpoint.
        target_completion_tokens: Tokens generated by the target endpoint.
        judge_prompt_tokens: Tokens sent to the LLM judge.
        judge_completion_tokens: Tokens generated by the LLM judge.
        total_tokens: Total tokens consumed (target + judge).
    """
    payload: Payload
    response_text: str
    vulnerable: bool
    severity: str
    confidence: float = 1.0
    judge_type: str = "heuristic"
    reasoning: str = ""
    error: Optional[str] = None
    converter_used: Optional[str] = None
    original_prompt: Optional[str] = None
    likert_score: int = 0
    sent_prompt: Optional[str] = None
    target_prompt_tokens: int = 0
    target_completion_tokens: int = 0
    judge_prompt_tokens: int = 0
    judge_completion_tokens: int = 0
    total_tokens: int = 0

    def to_dict(self) -> Dict[str, Any]:
        """Convert Finding instance to dictionary."""
        return {
            "payload": self.payload.to_dict(),
            "response_text": self.response_text,
            "vulnerable": self.vulnerable,
            "severity": self.severity,
            "confidence": self.confidence,
            "judge_type": self.judge_type,
            "reasoning": self.reasoning,
            "error": self.error,
            "converter_used": self.converter_used,
            "original_prompt": self.original_prompt,
            "likert_score": self.likert_score,
            "sent_prompt": self.sent_prompt,
            "target_prompt_tokens": self.target_prompt_tokens,
            "target_completion_tokens": self.target_completion_tokens,
            "judge_prompt_tokens": self.judge_prompt_tokens,
            "judge_completion_tokens": self.judge_completion_tokens,
            "total_tokens": self.total_tokens,
        }


@dataclass
class ScanResult:
    """Represents complete scan results for a security audit run.

    Attributes:
        target_url: The API endpoint URL scanned.
        start_time: ISO-8601 formatted start timestamp.
        end_time: ISO-8601 formatted end timestamp.
        total_payloads: Total number of payloads executed.
        findings: List of Finding results.
        circuit_broken: Indicates whether scan stopped prematurely due to failures.
        duration_seconds: Scan execution duration in seconds.
        likert_distribution: Frequency count of Likert scores (0 to 4).
        posture_score: Overall security posture score (0 to 100).
        grade: Letter grade rating (A, B, C, D, F).
        category_scores: Sub-scores by OWASP category.
        total_target_tokens: Cumulative tokens consumed by target endpoint (prompt + completion).
        total_judge_tokens: Cumulative tokens consumed by LLM judge.
        total_tokens: Total tokens consumed across entire scan.
        judge_tokens_saved: Estimated tokens saved by fast heuristic/signature short-circuiting.
    """
    target_url: str
    start_time: str
    end_time: str
    total_payloads: int
    findings: List[Finding] = field(default_factory=list)
    circuit_broken: bool = False
    duration_seconds: float = 0.0
    likert_distribution: Dict[int, int] = field(default_factory=dict)
    posture_score: float = 100.0
    grade: str = "A"
    category_scores: Dict[str, float] = field(default_factory=dict)
    total_target_tokens: int = 0
    total_judge_tokens: int = 0
    total_tokens: int = 0
    judge_tokens_saved: int = 0

    @property
    def vulnerable_count(self) -> int:
        """Count total findings flagged as vulnerable."""
        return sum(1 for f in self.findings if f.vulnerable)

    @property
    def severity_counts(self) -> Dict[str, int]:
        """Return counts of vulnerable findings broken down by severity."""
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for f in self.findings:
            if f.vulnerable:
                sev = f.severity.upper()
                if sev in counts:
                    counts[sev] += 1
                else:
                    counts[sev] = 1
        return counts

    def to_dict(self) -> Dict[str, Any]:
        """Convert ScanResult instance to dictionary."""
        return {
            "target_url": self.target_url,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "total_payloads": self.total_payloads,
            "vulnerable_count": self.vulnerable_count,
            "severity_counts": self.severity_counts,
            "circuit_broken": self.circuit_broken,
            "duration_seconds": self.duration_seconds,
            "likert_distribution": self.likert_distribution,
            "posture_score": self.posture_score,
            "grade": self.grade,
            "category_scores": self.category_scores,
            "total_target_tokens": self.total_target_tokens,
            "total_judge_tokens": self.total_judge_tokens,
            "total_tokens": self.total_tokens,
            "judge_tokens_saved": self.judge_tokens_saved,
            "findings": [f.to_dict() for f in self.findings],
        }


@dataclass
class ConversationTurn:
    """Represents a single dialogue turn in a multi-turn conversation."""
    turn_number: int
    role: str  # 'attacker' | 'target'
    content: str
    timestamp: float
    prompt_tokens: int = 0
    completion_tokens: int = 0

    def to_dict(self) -> Dict[str, Any]:
        """Convert ConversationTurn instance to dictionary."""
        return {
            "turn_number": self.turn_number,
            "role": self.role,
            "content": self.content,
            "timestamp": self.timestamp,
            "prompt_tokens": self.prompt_tokens,
            "completion_tokens": self.completion_tokens,
        }


@dataclass
class MultiTurnPayload:
    """Represents a scenario for multi-turn adversarial red-teaming."""
    id: str
    category: str
    owasp_id: str
    severity: str
    opening_prompt: str
    escalation_strategy: str
    stop_condition_hint: str
    max_turns: int = 4

    def to_dict(self) -> Dict[str, Any]:
        """Convert MultiTurnPayload instance to dictionary."""
        return {
            "id": self.id,
            "category": self.category,
            "owasp_id": self.owasp_id,
            "severity": self.severity,
            "max_turns": self.max_turns,
            "opening_prompt": self.opening_prompt,
            "escalation_strategy": self.escalation_strategy,
            "stop_condition_hint": self.stop_condition_hint,
        }


@dataclass
class MultiTurnFinding:
    """Represents the evaluation outcome of a multi-turn attack scenario."""
    payload_id: str
    category: str
    owasp_id: str
    vulnerable: bool
    severity: str
    confidence: float
    reasoning: str
    full_transcript: List[ConversationTurn] = field(default_factory=list)
    succeeded_at_turn: Optional[int] = None
    error: Optional[str] = None
    likert_score: int = 0
    attack_strategy: str = ""
    stop_condition_hint: str = ""
    breached_vulnerabilities: List[str] = field(default_factory=list)
    breach_factors: List[str] = field(default_factory=list)
    target_prompt_tokens: int = 0
    target_completion_tokens: int = 0
    judge_prompt_tokens: int = 0
    judge_completion_tokens: int = 0
    total_tokens: int = 0

    def to_dict(self) -> Dict[str, Any]:
        """Convert MultiTurnFinding instance to dictionary."""
        return {
            "payload_id": self.payload_id,
            "category": self.category,
            "owasp_id": self.owasp_id,
            "vulnerable": self.vulnerable,
            "severity": self.severity,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "succeeded_at_turn": self.succeeded_at_turn,
            "error": self.error,
            "likert_score": self.likert_score,
            "attack_strategy": self.attack_strategy,
            "stop_condition_hint": self.stop_condition_hint,
            "breached_vulnerabilities": self.breached_vulnerabilities,
            "breach_factors": self.breach_factors,
            "target_prompt_tokens": self.target_prompt_tokens,
            "target_completion_tokens": self.target_completion_tokens,
            "judge_prompt_tokens": self.judge_prompt_tokens,
            "judge_completion_tokens": self.judge_completion_tokens,
            "total_tokens": self.total_tokens,
            "full_transcript": [t.to_dict() for t in self.full_transcript],
        }
